[package]
name = "admin-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
client = { path = "../client/", package = "client-app" }
protocol = { path = "../protocol/" }
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1"
tracing = { version = "0.1.43" }
tracing-subscriber = { version = "0.3.22" }
async-stream = "0.3"
